openapi: 3.0.1
info:
  title: API Authorization Service
  version: v0.9
servers:
  - url: http://localhost:28000
    description: Generated server url
paths:
  /api/logout:
    post:
      tags:
        - authorization-controller
      summary: Logout
      description: Logout from the system
      operationId: logout
      responses:
        '200':
          description: Successful logout
  /api/login:
    post:
      tags:
        - authorization-controller
      summary: Login
      description: Login to the system
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DtoAuthenticationRequest'
        required: true
      responses:
        '200':
          description: Successful login
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DtoAuthenticationResponse'
components:
  schemas:
    DtoAuthenticationRequest:
      type: object
      properties:
        email:
          type: string
          description: email
          example: admin@mail.com
        password:
          type: string
          description: password
          example: admin
    DtoAuthenticationResponse:
      type: object
      properties:
        email:
          type: string
          description: email
          example: user@mail.com
        token:
          type: string
          description: token
          example: sgvV1rCAKCKJBA.DAOJsdfCAjsncjnoaoJOIh.JasdOAIadSCancF4oaio
